### ISSUE TITLE
Release v1

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/build-openj9#11]
We need to release v1 to enable the nightly build or publish the action to be used in other workflow. @smlambert I don't have permission to do it. Could you help with this?

**Comment by smlambert** [comment]
Done, @sophia-guo please let me know if you find any issues with initial release: https://github.com/eclipse/build-openj9/releases/tag/v1.0

**Comment by sophia-guo** [comment]
@smlambert We would also tag the current release v1.0 as tag v1 to be consumed by github action workflows( we could use release v1.0 as tag though normally github action normally use v1, v2 as tag name convention)

To create a tag on current v1.0 release we can just click on edit button for the v1.0 release, provide v1 as tag name and click on "Update Release". This will create a new Tag within the existing Release. Thanks!

**Comment by smlambert** [comment]
thanks @sophia-guo, done!
