### ISSUE TITLE
Fix failures on nightly scheduled builds

### ISSUE THREAD

**Issue by smlambert** [eclipse/build-openj9#4]
I believe we have a 2nd PR that needs to be merged in order for nightlies to pass:

https://github.com/eclipse/build-openj9/actions

**Comment by smlambert** [comment]
FYI @sophia-guo

**Comment by sophia-guo** [comment]
Yes, I will make a PR to add other related files, mainly MIT license files.

Also need to do a release for nightly to consume.

**Comment by smlambert** [comment]
All failing with Unable to resolve action `eclipse/build-openj9@v1

@sophia-guo - was I supposed to take an action here, or can you do a release?

**Comment by sophia-guo** [comment]
v1 has been released last Nov. I didn't see the the failure of `failing with Unable to resolve action `eclipse/build-openj9@v1

`? Could you please point me to the failure?

**Comment by smlambert** [comment]
yes sorry, I was looking at a run from 3months ago... thanks for creating issues on some of the recent failures...  

I know they are rolling out more build changes (cmake stuff), I presume the build instructions are also being updated, and have not looked at the failures in this repo yet so do not know if there is a relationship or not.

**Comment by sophia-guo** [comment]
With jdk 16 enabled all issues should have been tracked by separated issues. This one is related with the release v1 and MIT licenses, which has been done. So I will close this one.
